name: lms_flutter_app
description: A new Flutter project.
publish_to: 'none'

version: 1.7.3+47

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  dio: ^4.0.0-beta7
  permission_handler: ^8.3.0
  flutter_svg: ^1.1.5
  dropdown_below: ^0.0.6
  dropdown_search: ^5.0.6
  toast: ^0.3.0
  http: ^0.13.1
  get: ^4.6.5
  auto_size_text: ^3.0.0
  get_storage: ^2.0.2
  flutter_rating_bar: ^4.0.0
  shared_preferences: ^2.0.5
  flutter_portal: ^0.4.0
  reactive_forms: 10.1.0
  extended_nested_scroll_view: ^6.0.0
  font_awesome_flutter: ^9.0.0
  flutter_widget_from_html_core: ^0.10.1
  firebase_core_platform_interface: 4.5.1
  persistent_bottom_nav_bar: ^5.0.2
  loading_skeleton_niu: ^0.0.1
  flutter_cache_manager: ^3.0.2
  file_picker: ^5.0.1
  file_utils: ^1.0.0
  file: ^6.1.4
  url_launcher: ^6.0.6
  flutter_screenutil: ^5.0.0+2
  http_auth: ^1.0.0
  flutter_switch: ^0.3.2
  slide_countdown: ^0.0.4
  chips_choice: ^3.0.0
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1
  rxdart: ^0.26.0
  edge_alerts: ^0.0.1
  percent_indicator: ^3.4.0
  loader_overlay: ^2.0.2+1
  flutter_spinkit: ^5.1.0
  razorpay_flutter: ^1.2.7
  open_document:
    git: https://github.com/emran92/open_document
  advance_pdf_viewer:
    git:
      url: https://github.com/lohanidamodar/pdf_viewer.git
      ref: 4e5d96be29de515f1081c0b6897741b8dca84722
  webview_flutter: ^4.2.1
  flutter_facebook_auth: ^4.1.1
  google_sign_in: ^5.2.4
  connection_notifier: ^0.0.1
  flutter_inappwebview:
  vdocipher_flutter: ^1.0.0-beta.6
  flutter_paystack: ^1.0.7
  eko_jitsi:
    path: ./eko_jitsi
  fancy_shimmer_image: ^2.0.2
  purchases_flutter: ^4.2.1
  pod_player:
  google_fonts: ^4.0.4
  transparent_image: ^2.0.0
  octo_image: ^1.0.2
  awesome_notifications: ^0.6.21
  another_flushbar: ^1.12.29
  sign_in_with_apple: ^4.3.0
  crypto: ^3.0.3
  youtube_player_iframe: ^4.0.4
  youtube_player_flutter: ^8.1.2


  #  removed packages ----------->
  #  flutter_paystack:
  #    git:
  #      url: https://github.com/definitelyme/flutter_paystack.git
  #      ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01

  #  eko_jitsi:
  #    git: https://github.com/emran92/eko_jitsi
  #  sn_progress_dialog: ^1.0.8
  #advance_pdf_viewer: ^2.0.0
#  flutter_webview_plugin: ^0.4.0
#  loading_skeleton: ^1.0.2
#  smart_select: ^4.3.2
#  edge_alert: ^0.0.1
#  package_info_plus: ^4.0.2

dependency_overrides:
  # freezed_annotation: ^2.0.1
  package_info_plus_windows:
    path: ./package_info_plus_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  import_sorter: ^4.6.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.jpg"

flutter_native_splash:
  background_image: "images/Splash.png"
  fullscreen: false

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: AvenirNext
      fonts:
        - asset: font/AvenirNextLTPro-Regular.otf
