name: package_info_plus_windows
description: Windows implementation of the package_info_plus plugin
version: 2.1.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  package_info_plus_platform_interface: ^1.0.2
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  win32: ">=2.7.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    implements: package_info_plus
    platforms:
      windows:
        dartPluginClass: PackageInfoWindows
        pluginClass: none
